	

'//---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------//
'.................Test Script Name :[1]Test_PRE_VIM Role determination_New
'.................Author : TCS 
'................ Creation Date : 02/05/2025
'.................Modified By : Jaya Chandra
'.................Modified Date/Details : 02/05/2025 - TAO to TASE migration

'//---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------//

If qtpParamExist("gstrInputExcelFilePathAndName") Then
	gstrInputExcelFilePathAndName= Parameter("gstrInputExcelFilePathAndName")	
End If

If qtpParamExist("gstrresultFolderPath") Then
	gstrresultFolderPath= Parameter("gstrresultFolderPath")	
End If

If qtpParamExist("datatable_row") Then
	DataRowSet= Parameter("datatable_row")	
End If

If qtpParamExist("RunTimeResultFolder") Then
	RunTimeResultFolder= Parameter("RunTimeResultFolder")	
End If

gstrresultFolderPath =  ReadTxtFileResult(RunTimeResultFolder)

gstrTestCaseName = "Test_PRE_VIM Role determination_New"
gstrTCDescription = ""'.....Please give TestCase Description.
gstrTCPrerequisite = ""'.....Please mention the pre-requisites for TestCase If any.
'gstrInputExcelFilePathAndName="S:\TASETestData\AB\RETAIL\DT_07.01.05.02.07 Transfer posting for Set articles sent to photogr_TASE.xls"


'//---------------------------------------------------------------------------------------------------------------------------------------------------AUTOMATION TEST SCRIPT------------------------------------------------------------------------------------------------------------------------------------------------------------//

'DataRowSet =2
Call StartExecution(gstrInputExcelFilePathAndName,"Global",DataRowSet,gstrresultFolderPath) 

'Call LaunchSAPConnection("C:\Program Files (x86)\SAP\FrontEnd\SAPgui\saplogon.exe",DT_SAPSYSTEM)
Call SAPGuiUtil.OpenConnection(DT_SAPSYSTEM)
Call Login(DT_SAPUSER,DT_SAPPASSWORD)
Call PressEnter() 


Call SetTcode(DT_SAPTRANSACTIONCODE) 
Call PressEnter()
Call CheckTCodeScreen(DT_SAPTRANSACTIONCODE)

'//----------------------------------- /OPT/CP_9CX4 -----------------------------------
Call TakeScreenshot()
Call ClickLinkGuiTree( "Product Code;005-Open Text Document Processing 5i;#2", DT_NODE1,"", False)
Call TakeScreenshot()
Call ClickButton("Display / Change   \(F6\)", False)
Call TakeScreenshot()
Call GetNumberOfRows("Shell", "", "NumOfRows")
Call ClickButtonToolBar("MLINE","")
Call TakeScreenshot()

Call SetGridData("", NumOfRows+1, "Company Code", DT_CO_CODE_1, False)
Call SetGridData("", NumOfRows+1, "Agent Type", DT_OTYPE_1, False)
Call SetGridData("", NumOfRows+1, "Agent ID", DT_OBJID_1, False)
Call TakeScreenshot()
Call ClickButton("Save   \(Ctrl\+S\)",FALSE)
Call TakeScreenshot()
Call ClickButtonifExist("Yes",True)
Call TakeScreenshot()

Call ClickButtonToolBar("MLINE","")
Call SetGridData("", NumOfRows+2, "Company Code", DT_CO_CODE_2, False)
Call SetGridData("", NumOfRows+2, "Agent Type", DT_OTYPE_2, False)
Call SetGridData("", NumOfRows+2, "Agent ID", DT_OBJID_2, False)
Call TakeScreenshot()
Call ClickButton("Save   \(Ctrl\+S\)",FALSE)
Call TakeScreenshot()
Call ClickButtonifExist("Yes",True)
Call TakeScreenshot()

Call ClickButtonToolBar("MLINE","")
Call SetGridData("", NumOfRows+3, "Company Code", DT_CO_CODE_3, False)
Call SetGridData("", NumOfRows+3, "Agent Type", DT_OTYPE_3, False)
Call SetGridData("", NumOfRows+3, "Agent ID", DT_OBJID_3, False)
Call TakeScreenshot()
Call ClickButton("Save   \(Ctrl\+S\)",FALSE)
Call TakeScreenshot()
Call ClickButtonifExist("Yes",True)
Call TakeScreenshot()
Call ClickButton("Refresh   \(Shift\+F8\)",False)

Call ClickLinkGuiTree( "Product Code;005-Open Text Document Processing 5i;#7","GENPACT        -Genpact","", False)
Call TakeScreenshot()
Call ClickButton("Display / Change   \(F6\)", False)
Call TakeScreenshot()
Call GetNumberOfRows("Shell", "", "NumOfRows")
Call TakeScreenshot()
Call ClickButtonToolBar("MLINE","")
Call TakeScreenshot()

Call SetGridData("", NumOfRows+1, "Document type", DT_VALIDATOR_1, False)
Call SetGridData("", NumOfRows+1, "Company Code", DT_CO_CODE_1, False)
Call SetGridData("", NumOfRows+1, "Agent Type", DT_OTYPE_1, False)
Call SetGridData("", NumOfRows+1, "Agent ID", DT_OBJID_1, False)
Call SetGridData("", NumOfRows+1, "DP Document Type", DT_SPECIAL, False)
Call TakeScreenshot()
Call ClickButton("Save   \(Ctrl\+S\)",FALSE)
Call TakeScreenshot()
Call ClickButtonifExist("Yes",True)
Call TakeScreenshot()

Call ClickButtonToolBar("MLINE","")
Call SetGridData("", NumOfRows+2, "Document type", DT_VALIDATOR_2, False)
Call SetGridData("", NumOfRows+2, "Company Code", DT_CO_CODE_2, False)
Call SetGridData("", NumOfRows+2, "Agent Type", DT_OTYPE_2, False)
Call SetGridData("", NumOfRows+2, "Agent ID", DT_OBJID_2, False)
Call SetGridData("", NumOfRows+2, "DP Document Type", DT_SPECIAL, False)
Call TakeScreenshot()
Call ClickButton("Save   \(Ctrl\+S\)",FALSE)
Call TakeScreenshot()
Call ClickButtonifExist("Yes",True)
Call TakeScreenshot()

Call ClickButtonToolBar("MLINE","")
Call SetGridData("", NumOfRows+3, "Document type", DT_VALIDATOR_3, False)
Call SetGridData("", NumOfRows+3, "Company Code", DT_CO_CODE_3, False)
Call SetGridData("", NumOfRows+3, "Agent Type", DT_OTYPE_3, False)
Call SetGridData("", NumOfRows+3, "Agent ID", DT_OBJID_3, False)
Call SetGridData("", NumOfRows+3, "DP Document Type", DT_SPECIAL, False)
Call TakeScreenshot()
Call ClickButton("Save   \(Ctrl\+S\)",FALSE)
Call TakeScreenshot()
Call ClickButtonifExist("Yes",True)
Call TakeScreenshot()

Call ClickLinkGuiTree( "Product Code;005-Open Text Document Processing 5i;#10","MASTER_DATA    -Master Data","", False)
Call TakeScreenshot()
Call GetNumberOfRows("Shell", "", "NumOfRows")
Call TakeScreenshot()
Call ClickButtonToolBar("MLINE","")
Call TakeScreenshot()

Call SetGridData("", NumOfRows+1, "Company Code", DT_CO_CODE_1, False)
Call SetGridData("", NumOfRows+1, "Agent Type", DT_OTYPE_1, False)
Call SetGridData("", NumOfRows+1, "Agent ID", DT_OBJID_1, False)
Call TakeScreenshot()
Call ClickButton("Save   \(Ctrl\+S\)",FALSE)
Call TakeScreenshot()
Call ClickButtonifExist("Yes",True)
Call TakeScreenshot()

Call ClickButtonToolBar("MLINE","")
Call SetGridData("", NumOfRows+2, "Company Code", DT_CO_CODE_2, False)
Call SetGridData("", NumOfRows+2, "Agent Type", DT_OTYPE_2, False)
Call SetGridData("", NumOfRows+2, "Agent ID", DT_OBJID_2, False)
Call TakeScreenshot()
Call ClickButton("Save   \(Ctrl\+S\)",FALSE)
Call TakeScreenshot()
Call ClickButtonifExist("Yes",True)
Call TakeScreenshot()

Call ClickButtonToolBar("MLINE","")
Call SetGridData("", NumOfRows+3, "Company Code", DT_CO_CODE_3, False)
Call SetGridData("", NumOfRows+3, "Agent Type", DT_OTYPE_3, False)
Call SetGridData("", NumOfRows+3, "Agent ID", DT_OBJID_3, False)
Call TakeScreenshot()
Call ClickButton("Save   \(Ctrl\+S\)",FALSE)
Call TakeScreenshot()
Call ClickButtonifExist("Yes",True)
Call TakeScreenshot()

Call ClickLinkGuiTree("Product Code;005-Open Text Document Processing 5i;#16","TAX_EXPERT     -Tax Expert","", False)
Call TakeScreenshot()
Call GetNumberOfRows("Shell", "", "NumOfRows")
Call TakeScreenshot()
Call ClickButtonToolBar("MLINE","")
Call TakeScreenshot()

Call SetGridData("", NumOfRows+1, "Company Code", DT_CO_CODE_1, False)
Call SetGridData("", NumOfRows+1, "Agent Type", DT_OTYPE_1, False)
Call SetGridData("", NumOfRows+1, "Agent ID", DT_OBJID_1, False)
Call TakeScreenshot()
Call ClickButton("Save   \(Ctrl\+S\)",FALSE)
Call TakeScreenshot()
Call ClickButtonifExist("Yes",True)
Call TakeScreenshot()

Call ClickButtonToolBar("MLINE","")
Call SetGridData("", NumOfRows+2, "Company Code", DT_CO_CODE_2, False)
Call SetGridData("", NumOfRows+2, "Agent Type", DT_OTYPE_2, False)
Call SetGridData("", NumOfRows+2, "Agent ID", DT_OBJID_2, False)
Call TakeScreenshot()
Call ClickButton("Save   \(Ctrl\+S\)",FALSE)
Call TakeScreenshot()
Call ClickButtonifExist("Yes",True)
Call TakeScreenshot()

Call ClickButtonToolBar("MLINE","")
Call SetGridData("", NumOfRows+3, "Company Code", DT_CO_CODE_3, False)
Call SetGridData("", NumOfRows+3, "Agent Type", DT_OTYPE_3, False)
Call SetGridData("", NumOfRows+3, "Agent ID", DT_OBJID_3, False)
Call TakeScreenshot()
Call ClickButton("Save   \(Ctrl\+S\)",FALSE)
Call TakeScreenshot()
Call ClickButtonifExist("Yes",True)
Call TakeScreenshot()

Call ClickLinkGuiTree("Product Code;005-Open Text Document Processing 5i;#17","VALIDATOR      -Validator","", False)
Call TakeScreenshot()
Call GetNumberOfRows("Shell", "", "NumOfRows")
Call TakeScreenshot()
Call ClickButtonToolBar("MLINE","")
Call TakeScreenshot()

Call SetGridData("", NumOfRows+1, "Document type", DT_VALIDATOR_1, False)
Call SetGridData("", NumOfRows+1, "Agent Type", DT_OTYPE_1, False)
Call SetGridData("", NumOfRows+1, "Agent ID", DT_OBJID_1, False)
Call TakeScreenshot()
Call ClickButton("Save   \(Ctrl\+S\)",FALSE)
Call TakeScreenshot()
Call ClickButtonifExist("Yes",True)
Call TakeScreenshot()

Call ClickButtonToolBar("MLINE","")
Call SetGridData("", NumOfRows+2, "Document type", DT_VALIDATOR_2, False)
Call SetGridData("", NumOfRows+2, "Agent Type", DT_OTYPE_2, False)
Call SetGridData("", NumOfRows+2, "Agent ID", DT_OBJID_2, False)
Call TakeScreenshot()
Call ClickButton("Save   \(Ctrl\+S\)",FALSE)
Call TakeScreenshot()
Call ClickButtonifExist("Yes",True)
Call TakeScreenshot()

Call ClickButtonToolBar("MLINE","")
Call SetGridData("", NumOfRows+3, "Document type", DT_VALIDATOR_3, False)
Call SetGridData("", NumOfRows+3, "Agent Type", DT_OTYPE_3, False)
Call SetGridData("", NumOfRows+3, "Agent ID", DT_OBJID_3, False)
Call TakeScreenshot()
Call ClickButton("Save   \(Ctrl\+S\)",FALSE)
Call TakeScreenshot()
Call ClickButtonifExist("Yes",True)
Call TakeScreenshot()

Call ClickLinkGuiTree("Product Code;005-Open Text Document Processing 5i;#19","ZD_AP_CAPEX    -Dummy - AP Processor: CAPEX","", False)
Call TakeScreenshot()
Call GetNumberOfRows("Shell", "", "NumOfRows")
Call TakeScreenshot()
Call ClickButtonToolBar("MLINE","")
Call TakeScreenshot()

Call SetGridData("", NumOfRows+1, "Document type", DT_VALIDATOR_1, False)
Call SetGridData("", NumOfRows+1, "Company Code", DT_CO_CODE_1, False)
Call SetGridData("", NumOfRows+1, "Agent Type", DT_OTYPE_1, False)
Call SetGridData("", NumOfRows+1, "Agent ID", DT_OBJID_1, False)
Call TakeScreenshot()
Call ClickButton("Save   \(Ctrl\+S\)",FALSE)
Call TakeScreenshot()
Call ClickButtonifExist("Yes",True)
Call TakeScreenshot()

Call ClickButtonToolBar("MLINE","")
Call SetGridData("", NumOfRows+2, "Document type", DT_VALIDATOR_2, False)
Call SetGridData("", NumOfRows+2, "Company Code", DT_CO_CODE_2, False)
Call SetGridData("", NumOfRows+2, "Agent Type", DT_OTYPE_2, False)
Call SetGridData("", NumOfRows+2, "Agent ID", DT_OBJID_2, False)
Call TakeScreenshot()
Call ClickButton("Save   \(Ctrl\+S\)",FALSE)
Call TakeScreenshot()
Call ClickButtonifExist("Yes",True)
Call TakeScreenshot()

Call ClickButtonToolBar("MLINE","")
Call SetGridData("", NumOfRows+3, "Document type", DT_VALIDATOR_3, False)
Call SetGridData("", NumOfRows+3, "Company Code", DT_CO_CODE_3, False)
Call SetGridData("", NumOfRows+3, "Agent Type", DT_OTYPE_3, False)
Call SetGridData("", NumOfRows+3, "Agent ID", DT_OBJID_3, False)
Call TakeScreenshot()
Call ClickButton("Save   \(Ctrl\+S\)",FALSE)
Call TakeScreenshot()
Call ClickButtonifExist("Yes",True)
Call TakeScreenshot()
 
 
Call ClickLinkGuiTree("Product Code;005-Open Text Document Processing 5i;#20","ZD_AP_IP       -Dummy - AP Processor: IP invoices","", False)
Call TakeScreenshot()
Call GetNumberOfRows("Shell", "", "NumOfRows")
Call TakeScreenshot()
Call ClickButtonToolBar("MLINE","")
Call TakeScreenshot()

Call SetGridData("", NumOfRows+1, "Document type", DT_VALIDATOR_1, False)
Call SetGridData("", NumOfRows+1, "Company Code", DT_CO_CODE_1, False)
Call SetGridData("", NumOfRows+1, "Agent Type", DT_OTYPE_1, False)
Call SetGridData("", NumOfRows+1, "Agent ID", DT_OBJID_1, False)
Call TakeScreenshot()
Call ClickButton("Save   \(Ctrl\+S\)",FALSE)
Call TakeScreenshot()
Call ClickButtonifExist("Yes",True)
Call TakeScreenshot()

Call ClickButtonToolBar("MLINE","")
Call SetGridData("", NumOfRows+2, "Document type", DT_VALIDATOR_2, False)
Call SetGridData("", NumOfRows+2, "Company Code", DT_CO_CODE_2, False)
Call SetGridData("", NumOfRows+2, "Agent Type", DT_OTYPE_2, False)
Call SetGridData("", NumOfRows+2, "Agent ID", DT_OBJID_2, False)
Call TakeScreenshot()
Call ClickButton("Save   \(Ctrl\+S\)",FALSE)
Call TakeScreenshot()
Call ClickButtonifExist("Yes",True)
Call TakeScreenshot()

Call ClickButtonToolBar("MLINE","")
Call SetGridData("", NumOfRows+3, "Document type", DT_VALIDATOR_3, False)
Call SetGridData("", NumOfRows+3, "Company Code", DT_CO_CODE_3, False)
Call SetGridData("", NumOfRows+3, "Agent Type", DT_OTYPE_3, False)
Call SetGridData("", NumOfRows+3, "Agent ID", DT_OBJID_3, False)
Call TakeScreenshot()
Call ClickButton("Save   \(Ctrl\+S\)",FALSE)
Call TakeScreenshot()
Call ClickButtonifExist("Yes",True)
Call TakeScreenshot()

Call ClickLinkGuiTree("Product Code;005-Open Text Document Processing 5i;#21","ZD_AP_NPO      -Dummy - AP Processor: NPO invoices","", False)
Call TakeScreenshot()
Call GetNumberOfRows("Shell", "", "NumOfRows")
Call TakeScreenshot()
Call ClickButtonToolBar("MLINE","")
Call TakeScreenshot()

Call SetGridData("", NumOfRows+1, "Document type", DT_VALIDATOR_1, False)
Call SetGridData("", NumOfRows+1, "Company Code", DT_CO_CODE_1, False)
Call SetGridData("", NumOfRows+1, "Agent Type", DT_OTYPE_1, False)
Call SetGridData("", NumOfRows+1, "Agent ID", DT_OBJID_1, False)
Call SetGridData("", NumOfRows+1, "DP Document Type", DT_SPECIAL, False)
Call TakeScreenshot()
Call ClickButton("Save   \(Ctrl\+S\)",FALSE)
Call TakeScreenshot()
Call ClickButtonifExist("Yes",True)
Call TakeScreenshot()

Call ClickButtonToolBar("MLINE","")
Call SetGridData("", NumOfRows+2, "Document type", DT_VALIDATOR_2, False)
Call SetGridData("", NumOfRows+2, "Company Code", DT_CO_CODE_2, False)
Call SetGridData("", NumOfRows+2, "Agent Type", DT_OTYPE_2, False)
Call SetGridData("", NumOfRows+2, "Agent ID", DT_OBJID_2, False)
Call SetGridData("", NumOfRows+2, "DP Document Type", DT_SPECIAL, False)
Call TakeScreenshot()
Call ClickButton("Save   \(Ctrl\+S\)",FALSE)
Call TakeScreenshot()
Call ClickButtonifExist("Yes",True)
Call TakeScreenshot()

Call ClickButtonToolBar("MLINE","")
Call SetGridData("", NumOfRows+3, "Document type", DT_VALIDATOR_3, False)
Call SetGridData("", NumOfRows+3, "Company Code", DT_CO_CODE_3, False)
Call SetGridData("", NumOfRows+3, "Agent Type", DT_OTYPE_3, False)
Call SetGridData("", NumOfRows+3, "Agent ID", DT_OBJID_3, False)
Call SetGridData("", NumOfRows+3, "DP Document Type", DT_SPECIAL, False)
Call TakeScreenshot()
Call ClickButton("Save   \(Ctrl\+S\)",FALSE)
Call TakeScreenshot()
Call ClickButtonifExist("Yes",True)
Call TakeScreenshot()
 
Call ClickLinkGuiTree("Product Code;005-Open Text Document Processing 5i;#22","ZD_AP_OPEX     -Dummy - AP Processor: OPEX","", False)
Call TakeScreenshot()
Call GetNumberOfRows("Shell", "", "NumOfRows")
Call TakeScreenshot()
Call ClickButtonToolBar("MLINE","")
Call TakeScreenshot()

Call SetGridData("", NumOfRows+1, "Document type", DT_VALIDATOR_1, False)
Call SetGridData("", NumOfRows+1, "Company Code", DT_CO_CODE_1, False)
Call SetGridData("", NumOfRows+1, "Agent Type", DT_OTYPE_1, False)
Call SetGridData("", NumOfRows+1, "Agent ID", DT_OBJID_1, False)
Call TakeScreenshot()
Call ClickButton("Save   \(Ctrl\+S\)",FALSE)
Call TakeScreenshot()
Call ClickButtonifExist("Yes",True)
Call TakeScreenshot()

Call ClickButtonToolBar("MLINE","")
Call SetGridData("", NumOfRows+2, "Document type", DT_VALIDATOR_2, False)
Call SetGridData("", NumOfRows+2, "Company Code", DT_CO_CODE_2, False)
Call SetGridData("", NumOfRows+2, "Agent Type", DT_OTYPE_2, False)
Call SetGridData("", NumOfRows+2, "Agent ID", DT_OBJID_2, False)
Call TakeScreenshot()
Call ClickButton("Save   \(Ctrl\+S\)",FALSE)
Call TakeScreenshot()
Call ClickButtonifExist("Yes",True)
Call TakeScreenshot()

Call ClickButtonToolBar("MLINE","")
Call SetGridData("", NumOfRows+3, "Document type", DT_VALIDATOR_3, False)
Call SetGridData("", NumOfRows+3, "Company Code", DT_CO_CODE_3, False)
Call SetGridData("", NumOfRows+3, "Agent Type", DT_OTYPE_3, False)
Call SetGridData("", NumOfRows+3, "Agent ID", DT_OBJID_3, False)
Call TakeScreenshot()
Call ClickButton("Save   \(Ctrl\+S\)",FALSE)
Call TakeScreenshot()
Call ClickButtonifExist("Yes",True)
Call TakeScreenshot()

Call ClickLinkGuiTree("Product Code;005-Open Text Document Processing 5i;#25","ZD_AP_RET      -Dummy - AP Processor: Retail invoices","", False)
Call TakeScreenshot()
Call GetNumberOfRows("Shell", "", "NumOfRows")
Call TakeScreenshot()
Call ClickButtonToolBar("MLINE","")
Call TakeScreenshot()

Call SetGridData("", NumOfRows+1, "Document type", DT_VALIDATOR_1, False)
Call SetGridData("", NumOfRows+1, "Company Code", DT_CO_CODE_1, False)
Call SetGridData("", NumOfRows+1, "Agent Type", DT_OTYPE_1, False)
Call SetGridData("", NumOfRows+1, "Agent ID", DT_OBJID_1, False)
Call TakeScreenshot()
Call ClickButton("Save   \(Ctrl\+S\)",FALSE)
Call TakeScreenshot()
Call ClickButtonifExist("Yes",True)
Call TakeScreenshot()

Call ClickButtonToolBar("MLINE","")
Call SetGridData("", NumOfRows+2, "Document type", DT_VALIDATOR_2, False)
Call SetGridData("", NumOfRows+2, "Company Code", DT_CO_CODE_2, False)
Call SetGridData("", NumOfRows+2, "Agent Type", DT_OTYPE_2, False)
Call SetGridData("", NumOfRows+2, "Agent ID", DT_OBJID_2, False)
Call TakeScreenshot()
Call ClickButton("Save   \(Ctrl\+S\)",FALSE)
Call TakeScreenshot()
Call ClickButtonifExist("Yes",True)
Call TakeScreenshot()

Call ClickButtonToolBar("MLINE","")
Call SetGridData("", NumOfRows+3, "Document type", DT_VALIDATOR_3, False)
Call SetGridData("", NumOfRows+3, "Company Code", DT_CO_CODE_3, False)
Call SetGridData("", NumOfRows+3, "Agent Type", DT_OTYPE_3, False)
Call SetGridData("", NumOfRows+3, "Agent ID", DT_OBJID_3, False)
Call TakeScreenshot()
Call ClickButton("Save   \(Ctrl\+S\)",FALSE)
Call TakeScreenshot()
Call ClickButtonifExist("Yes",True)
Call TakeScreenshot()

Call ClickLinkGuiTree("Product Code;005-Open Text Document Processing 5i;#27","ZD_BUYER_IP_T  -Dummy - Buyer: IP Team","", False)
Call TakeScreenshot()
Call GetNumberOfRows("Shell", "", "NumOfRows")
Call TakeScreenshot()
Call ClickButtonToolBar("MLINE","")
Call TakeScreenshot()

Call SetGridData("", NumOfRows+1, "Document type", DT_VALIDATOR_1, False)
Call SetGridData("", NumOfRows+1, "Company Code", DT_CO_CODE_1, False)
Call SetGridData("", NumOfRows+1, "Agent Type", DT_OTYPE_1, False)
Call SetGridData("", NumOfRows+1, "Agent ID", DT_OBJID_1, False)
Call TakeScreenshot()
Call ClickButton("Save   \(Ctrl\+S\)",FALSE)
Call TakeScreenshot()
Call ClickButtonifExist("Yes",True)
Call TakeScreenshot()

Call ClickButtonToolBar("MLINE","")
Call SetGridData("", NumOfRows+2, "Document type", DT_VALIDATOR_2, False)
Call SetGridData("", NumOfRows+2, "Company Code", DT_CO_CODE_2, False)
Call SetGridData("", NumOfRows+2, "Agent Type", DT_OTYPE_2, False)
Call SetGridData("", NumOfRows+2, "Agent ID", DT_OBJID_2, False)
Call TakeScreenshot()
Call ClickButton("Save   \(Ctrl\+S\)",FALSE)
Call TakeScreenshot()
Call ClickButtonifExist("Yes",True)
Call TakeScreenshot()

Call ClickButtonToolBar("MLINE","")
Call SetGridData("", NumOfRows+3, "Document type", DT_VALIDATOR_3, False)
Call SetGridData("", NumOfRows+3, "Company Code", DT_CO_CODE_3, False)
Call SetGridData("", NumOfRows+3, "Agent Type", DT_OTYPE_3, False)
Call SetGridData("", NumOfRows+3, "Agent ID", DT_OBJID_3, False)
Call TakeScreenshot()
Call ClickButton("Save   \(Ctrl\+S\)",FALSE)
Call TakeScreenshot()
Call ClickButtonifExist("Yes",True)
Call TakeScreenshot()

Call ClickLinkGuiTree("Product Code;005-Open Text Document Processing 5i;#28","ZD_BUYER_IP_TT -Dummy - Buyer: IP Technical Team","", False)
Call TakeScreenshot()
Call GetNumberOfRows("Shell", "", "NumOfRows")
Call TakeScreenshot()
Call ClickButtonToolBar("MLINE","")
Call TakeScreenshot()

Call SetGridData("", NumOfRows+1, "Document type", DT_VALIDATOR_1, False)
Call SetGridData("", NumOfRows+1, "Company Code", DT_CO_CODE_1, False)
Call SetGridData("", NumOfRows+1, "Agent Type", DT_OTYPE_1, False)
Call SetGridData("", NumOfRows+1, "Agent ID", DT_OBJID_1, False)
Call TakeScreenshot()
Call ClickButton("Save   \(Ctrl\+S\)",FALSE)
Call TakeScreenshot()
Call ClickButtonifExist("Yes",True)
Call TakeScreenshot()

Call ClickButtonToolBar("MLINE","")
Call SetGridData("", NumOfRows+2, "Document type", DT_VALIDATOR_2, False)
Call SetGridData("", NumOfRows+2, "Company Code", DT_CO_CODE_2, False)
Call SetGridData("", NumOfRows+2, "Agent Type", DT_OTYPE_2, False)
Call SetGridData("", NumOfRows+2, "Agent ID", DT_OBJID_2, False)
Call TakeScreenshot()
Call ClickButton("Save   \(Ctrl\+S\)",FALSE)
Call TakeScreenshot()
Call ClickButtonifExist("Yes",True)
Call TakeScreenshot()

Call ClickButtonToolBar("MLINE","")
Call SetGridData("", NumOfRows+3, "Document type", DT_VALIDATOR_3, False)
Call SetGridData("", NumOfRows+3, "Company Code", DT_CO_CODE_3, False)
Call SetGridData("", NumOfRows+3, "Agent Type", DT_OTYPE_3, False)
Call SetGridData("", NumOfRows+3, "Agent ID", DT_OBJID_3, False)
Call TakeScreenshot()
Call ClickButton("Save   \(Ctrl\+S\)",FALSE)
Call TakeScreenshot()
Call ClickButtonifExist("Yes",True)
Call TakeScreenshot()

Call Logoff()
Call FinalStatus()

