RunAction "RunTimeResultFolder", oneIteration
RunAction "TC1_O2C_08_07_088_P1_VA01_TASE", oneIteration
RunAction "DataTransfer_1", oneIteration
RunAction "TC2_O2C_088_P2_XML_VBSS_TASE", oneIteration
RunAction "DataTransfer_2", oneIteration
RunAction "TC3_088_P3_XML_VBSCN_TASE", oneIteration
RunAction "DataTransfer_3", oneIteration
RunAction "TC4_088_P4_CheckIdoc_WE02_TASE", oneIteration
RunAction "DataTransfer_4", oneIteration
RunAction "Wait_TASE", oneIteration
RunAction "TC5_088_P5_VL03N_TASE", oneIteration
RunAction "TC6_088_P6_VF01_TASE", oneIteration
RunAction "DataTransfer_5", oneIteration
RunAction "TC7_088_P7_VF03_TASE", oneIteration
RunAction "DataTransfer_6", oneIteration
RunAction "TC8_088_P8_MB03_GI_TASE", oneIteration
RunAction "TC9_088_P9_VL03N_TASE", oneIteration
