RunAction "TC0_RunTimeResultFolder", oneIteration
RunAction "TC1_CAR_File_G032_F900_TASE", oneIteration
RunAction "TC2_CAR_File_G061_F900_TASE", oneIteration
RunAction "TC3_CAR_File_G032_F907_TASE", oneIteration
RunAction "TC4_CAR_File_G032_F916_TASE", oneIteration
RunAction "TC5_CAR_File_G032_F913_TASE", oneIteration
RunAction "TC6_CAR_File_G032_F914_TASE", oneIteration
RunAction "TC7_CAR_File_G032_F921_TASE", oneIteration
RunAction "TC8_CAR_File_G032_F919_TASE", oneIteration
RunAction "TC9_CAR_File_G061_S061_TASE", oneIteration
RunAction "TC10_CAR_File_G016_F912_TASE", oneIteration
RunAction "TC11_CAR_File_without_Arch_G061", oneIteration
RunAction "TC12_CAR_File_without_Arch_F219", oneIteration
RunAction "TC13_CAR_File_without_Arch_G003", oneIteration
RunAction "TC14_CAR_File_without_Arch_G603", oneIteration
RunAction "TC15_CAR_File_without_Arch_G039", oneIteration
RunAction "TC16_CAR_File_without_Arch_G606", oneIteration
RunAction "TC17_CAR_File_without_Arch_G003", oneIteration
RunAction "TC18_CAR_File_without_Arch_G142", oneIteration
RunAction "TC19_CAR_File_without_Arch_GW36", oneIteration
RunAction "TC20_DataTransfer_1", oneIteration
RunAction "TC21_Test_Approve_all_Transfers", oneIteration
